{{- if .Values.persistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
  {{- with .Values.persistentVolumeClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
  {{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
{{- end }}


