{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.persistentVolumeClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- if .Values.persistentVolumeClaim.accessModes }}
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  {{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  {{- end }}
  {{- if .Values.persistentVolumeClaim.volumeName }}
  volumeName: {{ .Values.persistentVolumeClaim.volumeName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size | default "10Gi" }}
{{- end }}

