apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zulip.fullname" . }}-redis
  labels:
    {{- include "zulip.redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  {{- if .Values.redis.persistence.volumeName }}
  volumeName: {{ .Values.redis.persistence.volumeName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}


