project: nexus
server: https://kubernetes.default.svc
repoURL: https://github.com/thisisamank/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  - name: jellyfin
    path: charts/core
    valueFiles:
      - ../../environments/core/jellyfin/values.yaml

  - name: flaresolverr
    path: charts/core
    valueFiles:
      - ../../environments/core/flaresolverr/values.yaml
  - name: jellyseerr
    path: charts/core
    valueFiles:
      - ../../environments/core/jellyseerr/values.yaml

  - name: ntfy
    path: charts/core
    valueFiles:
      - ../../environments/core/ntfy/values.yaml

  - name: prowlarr
    path: charts/core
    valueFiles:
      - ../../environments/core/prowlarr/values.yaml

  - name: radarr
    path: charts/core
    valueFiles:
      - ../../environments/core/radarr/values.yaml

  - name: sonarr
    path: charts/core
    valueFiles:
      - ../../environments/core/sonarr/values.yaml

  - name: qbittorrent
    path: charts/core
    valueFiles:
      - ../../environments/core/qbittorrent/values.yaml

  - name: longhorn-system
    path: charts/longhorn/1.10.1
    namespace: longhorn-system-akxr
    valueFiles:
      - ../../../environments/core/longhorn/values.yaml
