project: prod
server: https://kubernetes.default.svc
repoURL: https://github.com/thisisamank/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  - name: speedtest
    path: charts/production
    valueFiles:
      - ../../environments/production/speedtest/values.yaml
