project: prod
server: https://kubernetes.default.svc
repoURL: https://github.com/thisisamank/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  - name: speedtest
    path: charts/production
    valueFiles:
      - ../../environments/production/speedtest/values.yaml

  - name: production-postgresql
    path: charts/postgresql
    namespace: postgres
    valueFiles:
      - ../../environments/production/postgresql/values.yaml

  - name: production-redis
    namespace: redis
    path: charts/redis
    valueFiles:
      - ../../environments/production/redis/values.yaml

  - name: production-outline
    namespace: default
    path: charts/outline
    valueFiles:
      - ../../environments/production/outline/values.yaml
