project: staging
server: https://kubernetes.default.svc
repoURL: https://github.com/thisisamank/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  # - name: example
  #   path: charts/staging
  #   valueFiles:
  #     - ../../environments/staging/example/values.yaml

  - name: staging-postgresql
    namespace: postgres
    path: charts/postgresql
    valueFiles:
      - ../../environments/staging/postgresql/values.yaml

  - name: staging-redis
    namespace: redis
    path: charts/redis
    valueFiles:
      - ../../environments/staging/redis/values.yaml

  - name: staging-rabbitmq
    namespace: rabbitmq
    path: charts/rabbitmq
    valueFiles:
      - ../../environments/staging/rabbitmq/values.yaml

  - name: staging-immich
    namespace: immich
    path: charts/immich/0.10.3
    valueFiles:
      - ../../../environments/staging/immich/values.yaml

  - name: staging-n8n
    namespace: default
    path: charts/n8n/2.0.1
    valueFiles:
      - ../../../environments/staging/n8n/values.yaml
