project: staging
server: https://kubernetes.default.svc
repoURL: https://github.com/thisisamank/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  # - name: example
  #   path: charts/staging
  #   valueFiles:
  #     - ../../environments/staging/example/values.yaml

  - name: staging-postgresql
    namespace: postgres
    path: charts/postgresql
    valueFiles:
      - ../../environments/staging/postgresql/values.yaml
