project: staging
server: https://kubernetes.default.svc
repoURL: https://github.com/akxr-in/akxr-gitops
targetRevision: HEAD
namespace: default

apps:
  - name: example
    path: charts/staging
    valueFiles:
      - ../../environments/staging/example/values.yaml
