apiVersion: v2
name: karakeep
description: A Helm chart for Karakeep
type: application
version: 0.27.0
appVersion: 0.27.0
dependencies:
  - name: common
    version: 3.7.3
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: meilisearch
    version: 0.12.0
    repository: https://meilisearch.github.io/meilisearch-kubernetes
