apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ghost.service.type }}
  ports:
    - port: {{ .Values.ghost.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ghost.selectorLabels" . | nindent 4 }}

