apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost.fullname" . }}-content
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ghost.persistence.storageClass }}
  storageClassName: {{ .Values.ghost.persistence.storageClass }}
  {{- end }}
  {{- if .Values.ghost.persistence.volumeName }}
  volumeName: {{ .Values.ghost.persistence.volumeName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ghost.persistence.size }}

