apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ghost.fullname" . }}-mysql
  labels:
    {{- include "ghost.mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ghost.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "ghost.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ghost.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.mysqlExistingSecret }}
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ghost.mysqlExistingSecret }}
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.mysql.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.mysql.readinessProbe | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}

